# Generated by Django 3.1 on 2021-04-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiobook_title', models.CharField(max_length=100)),
                ('audiobook_author', models.CharField(max_length=100)),
                ('audiobook_narrator', models.CharField(max_length=100)),
                ('audiobook_duration', models.IntegerField()),
                ('audiobook_uploaded_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_name', models.CharField(max_length=100)),
                ('podcast_duration', models.IntegerField()),
                ('podcast_uploaded_time', models.DateTimeField()),
                ('podcast_host', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('song_duration', models.IntegerField()),
                ('song_uploaded_time', models.DateTimeField()),
            ],
        ),
    ]
